name: Local Build and Run
on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
jobs:
  # linters
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: make lint-frontend
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - run: make lint-backend
  lint:
    runs-on: ubuntu-latest
    needs: [lint-frontend, lint-backend]
    steps:
      - run: echo "done"
  # tests
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - run: make test-frontend
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - run: make test-backend
  test:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    steps:
      - run: echo "done"
  # release
  release:
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.0
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"
      - name: Build frontend
        run: make build-frontend
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build Docker image locally
      - name: Extract metadata for Docker
        id: meta
        run: |
          DOCKER_IMAGE=username/repo-name # Replace with your actual image name
          VERSION=${GITHUB_REF#refs/tags/}
          echo "IMAGE_NAME=${DOCKER_IMAGE}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${VERSION}" >> $GITHUB_ENV
  # Run container on self-hosted runner
  run-container:
    runs-on: self-hosted
    needs: [build-and-release]
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - name: Set environment variables
        run: |
          DOCKER_IMAGE=username/repo-name # Replace with your actual image name
          VERSION=${GITHUB_REF#refs/tags/}
          echo "IMAGE_NAME=${DOCKER_IMAGE}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${VERSION}" >> $GITHUB_ENV
      
      - name: Pull latest image
        run: docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      
      - name: Stop and remove existing container
        run: |
          docker stop filebrowser || true
          docker rm filebrowser || true
      
      - name: Run Docker container locally
        run: |
          # Run the Docker container with the specified format and volume mount to /app/uploads
          docker run -d \
            --name filebrowser \
            --user $(id -u):$(id -g) \
            -p 8080:8080 \
            -v /app/uploads:/data \
            -v $(pwd)/config:/config \
            -e FB_BASEURL=/filebrowser \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
          # Verify container is running
          docker ps
          
          # Optional: Show container logs
          docker logs filebrowser
